# 100 numpy exercises



#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__, np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BL

('1.25.1', None)

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros((10,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a.size * a.itemsize



32

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
a = np.zeros(10, dtype=int)
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
a[::-1]
np.flip(a)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
a = np.array([[0,1,2], [3,4,5], [6,7,8]])
a = np.arange(0, 9)
a.resize(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
a = np.array([1,2,0,0,4,0])
np.where(a>0)
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
np.identity(3)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
a = np.random.random(27)
a.resize(3, 3, 3)
a
np.random.random((3,3,3))

array([[[0.92188521, 0.18124187, 0.00167318],
        [0.42251669, 0.96788295, 0.57950469],
        [0.58052487, 0.53277236, 0.79888763]],

       [[0.66748274, 0.93844929, 0.63848326],
        [0.0158414 , 0.67713571, 0.45605073],
        [0.83991992, 0.98674275, 0.14599813]],

       [[0.10535756, 0.88926046, 0.81766094],
        [0.25775738, 0.0232343 , 0.04892449],
        [0.15228785, 0.81430772, 0.47867329]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
a = np.random.random((10,10))
print(np.min(a), np.max(a), np.resize(a, (5,5)))

0.0015410533087106826 0.9951394894267263 [[0.84781762 0.18260509 0.57273859 0.95567996 0.5693063 ]
 [0.47375668 0.43407568 0.34573574 0.8778061  0.09125493]
 [0.79198802 0.52349147 0.0231826  0.1743447  0.05108943]
 [0.34254507 0.2391004  0.87786053 0.49358863 0.6037948 ]
 [0.32935637 0.69530966 0.71138022 0.99513949 0.04425791]]


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
a = np.random.random(30)
np.mean(a)


0.5409862989148594

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
a = np.ones((4,4))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [15]:
a[[0, -1]]=0
a[:, [0, -1]]=0
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [16]:
np.nan in set([np.nan])

True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [17]:
b = np.random.random(25)
b.resize((5,5))
b = b.astype(np.int32)
b[4:5, 0:4]=[1,2,3,4]
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 2, 3, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
a = np.random.random(64)
b = 0
for i in range (len(a)):
    if b%2==0:
        a[i]=1
    b = b+1
a.resize((8,8))
a = a.astype(int)
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [19]:
# a = np.zeros((6,7,8))
flag = 0
d = []
for i in range (1, 7):
    for j in range(1, 8):
        for k in range(1, 9):
            if i*j*k==99:
                d = [i, j, k]
                flag = 1
                break
        if flag==1:
            break
    if flag==1:
        break
print(np.unravel_index(98,(6,7,8)))

(1, 5, 2)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [20]:
A = np.array([1, 0])
repetitions = (8, 4)  # Repeat A twice along the first axis and three times along the second axis.

tiled_array = np.tile(A, reps=repetitions)
print(tiled_array)

[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [21]:
a = np.random.random(25)
a.reshape(5, 5)
a = (a - a.min())/(a.max() - a.min())
a

array([0.82314085, 0.80460554, 0.62864793, 0.2027028 , 0.39512342,
       0.9053184 , 0.10902902, 0.        , 0.81269944, 1.        ,
       0.99933335, 0.21256629, 0.49568775, 0.77919082, 0.19357306,
       0.58369086, 0.14021346, 0.91575134, 0.26586776, 0.34803184,
       0.91434004, 0.18410821, 0.26373327, 0.03804815, 0.78567684])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [22]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
type(color)

numpy.dtypes.VoidDType

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [23]:
a = np.ones((5, 3))
b = np.zeros((3, 2))
np.dot(a, b)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
a = np.random.random(10)
a[3:9]=a[3:9]* -1
a


array([ 0.76015586,  0.01216773,  0.35183553, -0.39921036, -0.89425769,
       -0.91176659, -0.69891945, -0.69918028, -0.48432023,  0.86818131])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [25]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [26]:
# last one is illegal\


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
# nan
# 0
# [0.0]

#### 30. How to find common values between two arrays? (★☆☆)

In [28]:
a = np.random.randint((5, 5))
b = np.random.randint((5, 5))
c = np.intersect1d(a, b)
c

array([], dtype=int32)

#### 31. Create a NumPy array with elements from 1 to 10.? (★☆☆)

In [29]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [30]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\FCI1400\AppData\Local\Temp\ipykernel_13424\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [31]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2023-07-26 2023-07-27 2023-07-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [32]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [33]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a , b , ((a+b)*(-a/2)))

[[5 5]
 [1 4]] [[8 7]
 [4 5]] [[-32.5 -30. ]
 [ -2.5 -18. ]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [34]:
# Generate a random array of positive numbers between 0 and 10
random_array = np.random.rand(10) * 10

# Method 1: Floor function (round down to the nearest integer)
method1_result = np.floor(random_array)

# Method 2: Ceil function (round up to the nearest integer)
method2_result = np.ceil(random_array)

# Method 3: Truncate function (truncate towards zero)
method3_result = np.trunc(random_array)

# Method 4: Integer conversion (convert to integer, truncating decimal part)
method4_result = random_array.astype(int)

print("Random Array:", random_array)
print("Floor Function Result:", method1_result)
print("Ceil Function Result:", method2_result)
print("Truncate Function Result:", method3_result)
print("Integer Conversion Result:", method4_result)

Random Array: [7.61362557 6.78936235 7.91343722 1.30731409 3.05923784 7.26251617
 8.41436103 5.69678182 3.98496639 9.44633483]
Floor Function Result: [7. 6. 7. 1. 3. 7. 8. 5. 3. 9.]
Ceil Function Result: [ 8.  7.  8.  2.  4.  8.  9.  6.  4. 10.]
Truncate Function Result: [7. 6. 7. 1. 3. 7. 8. 5. 3. 9.]
Integer Conversion Result: [7 6 7 1 3 7 8 5 3 9]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [43]:
a = np.random.random((5, 5))
a[:, 0:1] = np.arange(0, 5).reshape((5,1))
a


array([[0.        , 0.7832322 , 0.98945255, 0.30990668, 0.71347443],
       [1.        , 0.3014719 , 0.44138625, 0.6635482 , 0.88587774],
       [2.        , 0.94440617, 0.41003457, 0.4634075 , 0.01777289],
       [3.        , 0.73323033, 0.99403653, 0.43361913, 0.69997204],
       [4.        , 0.72487284, 0.94825131, 0.41010822, 0.47182535]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [44]:
def generate_integers():
    for i in range(10):
        yield i

# Use np.fromiter() to build the array from the generator
array_from_generator = np.fromiter(generate_integers(), dtype=int)

print(array_from_generator)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [49]:
vector = np.linspace(0, 1, num=10, endpoint=False)[1:]

print(vector)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [61]:
a = np.random.random((10))
a.sort()
a

array([0.00407472, 0.04626264, 0.05803999, 0.12390072, 0.20188106,
       0.36915263, 0.41867954, 0.46760626, 0.7425096 , 0.75719641])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [65]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [71]:
a = np.random.random((2,2))
b = np.random.random((2,2))
equal = np.allclose(a,b)
print(equal)
equal = np.array_equal(a,b)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [75]:
Z = np.zeros(10)
Z.flags.writeable = False
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [94]:
a = np.arange(10)
print(a.max())
a[np.where(a==a.max())]=0
a

9


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

#### 46. Use boolean indexing to select elements of an array based on a condition. (★☆☆)

In [162]:
import numpy as np

# Create an example array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define a condition for selecting elements (e.g., select elements greater than 5)
condition = arr > 5
print(condition)

# Use boolean indexing to select elements that satisfy the condition
selected_elements = arr[condition]

print(selected_elements)

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [153]:

X = np.arange(8)
Y = X + 0.5
C = 1.0 / (X[:, np.newaxis] - Y)
print(C, np.linalg.det(C))
print(X[:, np.newaxis].shape, Y.shape)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]] 3638.163637117973
(8, 1) (8,)


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [156]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [96]:
a = np.random.random((4,4))
a = a.ravel()
for i in iter(a):
    print(i)

0.6563686726814744
0.12492378181148867
0.1281814502252253
0.6482842645639787
0.9624107756815313
0.7927574892968067
0.19770754862048923
0.07351705217985538
0.24026843028139122
0.7356228988819928
0.7363625163374088
0.25845910366875624
0.698313979749083
0.29849393536241464
0.08755875869665353
0.8268042595638635


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [100]:
a = np.random.random(10)
b = 0.410010
diff = abs(b-a[0])
val = 0
for i in a:
    if abs(b-i)<diff:
        diff = abs(b-i)
        val = np.where(a == i)
print('array', a)
print('index is', val)
print("value is", a[val])


array [0.96210916 0.5385056  0.37288627 0.06259749 0.42747971 0.86450577
 0.2366835  0.43207789 0.5071499  0.3383917 ]
index is (array([4], dtype=int64),)
value is [0.42747971]


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [159]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\FCI1400\AppData\Local\Temp\ipykernel_13424\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

*
**
***
****
*****
******
*******
********
*********
**********


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)